### ISSUE TITLE
When installing denali-typescript it errors when it cannot find modules

### ISSUE THREAD

**Issue by seawatts** [denali-js/denali-typescript#6]
denali install denali-typescript
cli v0.0.12 [local] | denali v0.0.29 [local]

✔ Addon package found
✔ Addon package installed
Running default blueprint for addon
already exists tsconfig.json
error This module isn't specified in a manifest.
postInstall failed:
Error: Command failed: yarn remove babel-eslint babel-plugin-syntax-async-functions babel-plugin-syntax-trailing-function-commas babel-plugin-transform-async-to-generator babel-plugin-transform-class-properties babel-plugin-transform-es2015-destructuring babel-plugin-transform-es2015-modules-commonjs babel-plugin-transform-es2015-shorthand-properties babel-plugin-transform-es2015-spread babel-plugin-transform-es2015-template-literals babel-plugin-transform-exponentiation-operator babel-plugin-transform-regenerator babel-plugin-transform-runtime denali-babel denali-eslint eslint-config-denali
error This module isn't specified in a manifest.

**Comment by davewasmer** [comment]
Closing as stale.

I'm unable to reproduce this issue, and given the lack of activity, I'm guessing it has since been fixed elsewhere.

Of course - if you are still impacted by this bug, feel free to leave a comment (ideally with a reproduction) and I'll reopen the issue.

**Comment by seawatts** [comment]
Hmm, not sure I haven't tried lately.
